name: Deploy to Production

# This triggers ONLY when code is merged into the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into GCP and Update Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          # This executes the script we will put on the server
          script: |
            bash /opt/samalink/scripts/deploy_prod.sh