from . import test_calculator
from . import test_workflow
from . import test_qa_fixes
from . import test_edara_client
from . import test_edara_sync_wizard
from . import test_branch_profit_promotion
from . import test_csv_import
from . import test_independent_line
from . import test_batch_merge
from . import test_receipt_report
from . import test_employee_self_service
